import { defineField, defineType } from "sanity";
import { altTextField, ctaFields } from "./objects";

export const homePage = defineType({
  name: "homePage",
  title: "Home Page",
  type: "document",
  groups: [
    { name: "hero", title: "Invitation hero" },
    { name: "welcome", title: "Welcome" },
    { name: "story", title: "Our story" },
    { name: "feature", title: "Feature quote" },
    { name: "previews", title: "Section previews" },
    { name: "rsvp", title: "Final RSVP" },
    { name: "visibility", title: "Section visibility" },
  ],
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Hero eyebrow text",
      type: "string",
      group: "hero",
      validation: (rule) => rule.max(40),
    }),
    defineField({
      name: "heroScript",
      title: "Hero script text",
      type: "string",
      group: "hero",
      description: "Decorative script word above the heading.",
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: "heroHeading",
      title: "Hero heading",
      type: "string",
      group: "hero",
      validation: (rule) =>
        rule.required().max(48).warning("Long headings may wrap awkwardly."),
    }),
    defineField({
      name: "heroSubheading",
      title: "Hero invitation line",
      type: "string",
      group: "hero",
      validation: (rule) => rule.required().max(120),
    }),
    defineField({
      name: "heroImage",
      title: "Hero image",
      type: "image",
      group: "hero",
      options: { hotspot: true },
      description: "Recommended horizontal image, at least 2400 × 1400 pixels.",
      fields: [altTextField],
      validation: (rule) =>
        rule.warning("Add a hero image before publishing for best results."),
    }),
    defineField({
      name: "primaryCta",
      title: "Primary button",
      type: "object",
      group: "hero",
      fields: ctaFields,
    }),
    defineField({
      name: "secondaryCta",
      title: "Secondary button",
      type: "object",
      group: "hero",
      fields: ctaFields,
    }),
    defineField({
      name: "welcomeScript",
      title: "Welcome script text",
      type: "string",
      group: "welcome",
    }),
    defineField({
      name: "welcomeHeading",
      title: "Welcome heading",
      type: "string",
      group: "welcome",
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: "welcomeMessage",
      title: "Welcome message",
      type: "text",
      rows: 5,
      group: "welcome",
      validation: (rule) => rule.required().max(800),
    }),
    defineField({
      name: "welcomeImage",
      title: "Welcome image",
      type: "image",
      group: "welcome",
      options: { hotspot: true },
      fields: [altTextField],
    }),
    defineField({
      name: "storyHeading",
      title: "Story heading",
      type: "string",
      group: "story",
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: "storyBody",
      title: "Story body",
      type: "text",
      rows: 6,
      group: "story",
      validation: (rule) => rule.required().max(1200),
    }),
    defineField({
      name: "storyAccentNote",
      title: "Story accent note",
      type: "string",
      group: "story",
    }),
    defineField({
      name: "storyImage",
      title: "Story image",
      type: "image",
      group: "story",
      options: { hotspot: true },
      fields: [altTextField],
      validation: (rule) =>
        rule.warning("Add a story image before publishing for best results."),
    }),
    defineField({
      name: "featureQuote",
      title: "Feature quote",
      type: "text",
      rows: 3,
      group: "feature",
      validation: (rule) => rule.required().max(280),
    }),
    defineField({
      name: "featureAttribution",
      title: "Quote attribution",
      type: "string",
      group: "feature",
    }),
    defineField({
      name: "featureImage",
      title: "Feature image",
      type: "image",
      group: "feature",
      options: { hotspot: true },
      fields: [altTextField],
      validation: (rule) =>
        rule.warning("Add a feature image before publishing for best results."),
    }),
    defineField({
      name: "schedulePreviewTitle",
      title: "Schedule preview title",
      type: "string",
      group: "previews",
    }),
    defineField({
      name: "schedulePreviewBody",
      title: "Schedule preview message",
      type: "text",
      rows: 3,
      group: "previews",
    }),
    defineField({
      name: "schedulePreviewCtaLabel",
      title: "Schedule preview button label",
      type: "string",
      group: "previews",
    }),
    defineField({
      name: "travelPreviewTitle",
      title: "Travel preview title",
      type: "string",
      group: "previews",
    }),
    defineField({
      name: "travelPreviewBody",
      title: "Travel preview message",
      type: "text",
      rows: 3,
      group: "previews",
    }),
    defineField({
      name: "travelPreviewCtaLabel",
      title: "Travel preview button label",
      type: "string",
      group: "previews",
    }),
    defineField({
      name: "travelPreviewHighlights",
      title: "Travel preview highlights",
      type: "array",
      of: [{ type: "string" }],
      group: "previews",
    }),
    defineField({
      name: "galleryPreviewTitle",
      title: "Gallery preview title",
      type: "string",
      group: "previews",
    }),
    defineField({
      name: "galleryPreviewBody",
      title: "Gallery preview message",
      type: "text",
      rows: 3,
      group: "previews",
    }),
    defineField({
      name: "galleryPreviewCtaLabel",
      title: "Gallery preview button label",
      type: "string",
      group: "previews",
    }),
    defineField({
      name: "rsvpFinaleTitle",
      title: "Final RSVP heading",
      type: "string",
      group: "rsvp",
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: "rsvpFinaleBody",
      title: "Final RSVP message",
      type: "text",
      rows: 3,
      group: "rsvp",
      validation: (rule) => rule.required().max(400),
    }),
    defineField({
      name: "rsvpFinaleCtaLabel",
      title: "Final RSVP button label",
      type: "string",
      group: "rsvp",
    }),
    defineField({
      name: "showWelcome",
      title: "Show welcome section",
      type: "boolean",
      group: "visibility",
      initialValue: true,
    }),
    defineField({
      name: "showStory",
      title: "Show story section",
      type: "boolean",
      group: "visibility",
      initialValue: true,
    }),
    defineField({
      name: "showCountdown",
      title: "Show countdown",
      type: "boolean",
      group: "visibility",
      initialValue: true,
    }),
    defineField({
      name: "showSchedulePreview",
      title: "Show schedule preview",
      type: "boolean",
      group: "visibility",
      initialValue: true,
    }),
    defineField({
      name: "showFeature",
      title: "Show feature quote",
      type: "boolean",
      group: "visibility",
      initialValue: true,
    }),
    defineField({
      name: "showTravelPreview",
      title: "Show travel preview",
      type: "boolean",
      group: "visibility",
      initialValue: true,
    }),
    defineField({
      name: "showGalleryPreview",
      title: "Show gallery preview",
      type: "boolean",
      group: "visibility",
      initialValue: true,
    }),
    defineField({
      name: "showRsvpFinale",
      title: "Show final RSVP section",
      type: "boolean",
      group: "visibility",
      initialValue: true,
    }),
  ],
  preview: {
    prepare: () => ({ title: "Home Page" }),
  },
});
